/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f084fe81-c0dd-48a5-af9b-6391b151f266",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ZN6VrTK2r",
    "aws_user_pools_web_client_id": "1t8oqsg1kvuja9u9rvd2r1a6o4",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://q4bxgttnhvgldoytn3m76gdye4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "vod-source-3netjtvtxz5j",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
